name:  Build and Push Images

on:
  schedule:
    - cron: '0 22 * * *'
  release:
    types:
      - published
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  dockerhub:
    uses: lcxznpy/CI/.github/workflows/image-build.yml@main
  
