name:  MO Checkin Regression(Standalone BVT)

on:
  pull_request_target:
    branches: [ main,'[0-9]+.[0-9]+*' ]
    types:
      - closed
    paths:
      - '**.go'
      - '**.c'
      - '**.h'

jobs:
  mo-checkin-regression:
    name: MO Checkin Regression(Standalone BVT)
    uses: lcxznpy/CI/.github/workflows/merge-trigger-standalone.yaml@change-set-go
    secrets: inherit
