name: WeWork Robot

# Controls when the workflow will run
on:
  issues:
    types: [closed, assigned, opened]
  schedule:
    - cron: '30 8 * * *'
  issue_comment:
    types: [created]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  issue-notify:
    uses: lcxznpy/CI/.github/workflows/robot.yml@main
